[package]
name = "rss_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking"] }
rss = "2.0"
anyhow = "1.0"
rodio = "0.20.1"
termion = "4.0.3"

[dev-dependencies]
tempfile = "3.8.1"
