[package]
name = "rss_reader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
rss = "2.0"
anyhow = "1.0"
rodio = "0.17"
termion = "2.0"

[dev-dependencies]
tempfile = "3.8.1"
